# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - fastparquet
  - seaborn
  - boto3
  - fs
  - pathlib
  - pip
  - pyprojroot