# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - pandas
    - fastparquet
    - scikit-learn
    - seaborn
    - boto3
    - fs
    - pathlib
    - pyprojroot